### ISSUE TITLE
phase2

### ISSUE THREAD

**Issue by bel28kent** [bel28kent/Mysterium#20]
This issue is for the branch to add phase2 edits to corpus.

**Comment by bel28kent** [comment]
@craigsapp Do I have your permission to add "!!!system-decoration: {(*)}" to the files you encoded? 
Also, how do you recommend encoding **dynam spines for piano music with three or four staves?

**Comment by craigsapp** [comment]
You can add a system decoration record to the files (you are allowed to do anything you want to the files, even if I disagree :-).   When there are two staves, the default is `!!!system-decotration: {(*)}` (so it is not necessary):

<img width="601" alt="Screenshot 2023-07-03 at 9 29 47 PM" src="https://github.com/bel28kent/Mysterium/assets/3487289/8d9bcbde-5b09-4679-a4a9-18bc59864853">

https://verovio.humdrum.org?t=KiprZXJuCSoqa2VybgoxQwkxY2MKPQk9CjFFCTFlCj0JPQoqLQkqLQohISFzeXN0ZW0tZGVjb3JhdGlvbjogeygqKX0K

<img width="624" alt="Screenshot 2023-07-03 at 9 30 56 PM" src="https://github.com/bel28kent/Mysterium/assets/3487289/95289880-e876-4d46-90b7-36aeb11a85fb">

https://verovio.humdrum.org?t=KiprZXJuCSoqa2VybgoxQwkxY2MKPQk9CjFFCTFlCj0JPQoqLQkqLQo=

For three or more staves, the default system decoration is:

```
!!!system-decoration: [*]
```

<img width="616" alt="Screenshot 2023-07-03 at 9 32 52 PM" src="https://github.com/bel28kent/Mysterium/assets/3487289/93800154-0667-40c6-8e9b-f6142fd2dea5">

(so bracket on the left across all staves, and barlines not connected between staves.

-------

For `**dynam` spines in three or for staves, you would place a `**dynam` spine immediately to the right of the `**kern` spine to which they are attached:

<img width="812" alt="Screenshot 2023-07-03 at 9 41 28 PM" src="https://github.com/bel28kent/Mysterium/assets/3487289/bbc203e2-19d8-492a-82dd-dabd6430429b">

https://verovio.humdrum.org?t=KiprZXJuCSoqa2VybgkqKmR5bmFtCSoqa2VybgkqKmR5bmFtCjFDCTFjYwlmCTFjYwlmCj0JPQk9CT0JPQoxRQkxZQlwCTFnCXAKPQk9CT0JPQk9CiotCSotCSotCSotCSotCiEhIXN5c3RlbS1kZWNvcmF0aW9uOiBbKCopXQo=

The above example is for single staff instruments but not for the grand staff.   For grand staff, place the `**dynam` spine to the immediate right of the top staff of the grand staff.   For double grand staff, there will be two `**dynam` spines: one to the right of each top staff:

<img width="956" alt="Screenshot 2023-07-03 at 9 56 03 PM" src="https://github.com/bel28kent/Mysterium/assets/3487289/592d9166-f359-49ce-a503-a2df436fee0e">

https://verovio.humdrum.org?t=KiprZXJuCSoqa2VybgkqKmR5bmFtCSoqa2VybgkqKmtlcm4JKipkeW5hbQoqc3RhZmY0CSpzdGFmZjMJKnN0YWZmMy80CSpzdGFmZjIJKnN0YWZmMQkqc3RhZmYxLzIKMUMJMWNjCXAgPiBdCTFjYwkxY2MJZiA8IFsKPQk9CT0JPQk9CT0KMUUJMWUJZgkxZwkxZwlwCj0JPQk9CT0JPQk9CiotCSotCSotCSotCSotCSotCiEhIXN5c3RlbS1kZWNvcmF0aW9uOiB7KHMxczIpfXsoczNzNCl9Cg==

The interpretations such as `*staff1/2` and `*staff3/4` means to center (by default) the dynamics between the two staves of the grand staff.  (You can instead add `*center` to the `**dynam` spine rather than using the `*staff1/2` system, but you need the staff labels for the system decoration record anyway.

There are complicated cases where a dynamic needs to be attached to the bottom staff (either above or below it).  In this case you can use a layout command such as `!LO:DY:a=2` or `!LO:DY:b=2` to display the following dynamic above or below the bottom staff of the grand staff:

<img width="942" alt="Screenshot 2023-07-03 at 10 07 55 PM" src="https://github.com/bel28kent/Mysterium/assets/3487289/bc2d9fb8-601c-46cd-858e-29d1134a32ba">

https://verovio.humdrum.org?t=KiprZXJuCSoqa2VybgkqKmR5bmFtCSoqa2VybgkqKmtlcm4JKipkeW5hbQoqc3RhZmY0CSpzdGFmZjMJKnN0YWZmMy80CSpzdGFmZjIJKnN0YWZmMQkqc3RhZmYxLzIKMUMJMWNjCXAJMWNjCTFjYwlmCiEJIQkhCSEJIQkhTE86RFk6YT0yCi4JLgkuCS4JLgltcAo9CT0JPQk9CT0JPQoxRQkxZQlmCTFnCTFnCXAKIQkhCSEJIQkhCSFMTzpEWTpiPTIKLgkuCS4JLgkuCXBwCj0JPQk9CT0JPQk9CiotCSotCSotCSotCSotCSotCiEhIXN5c3RlbS1kZWNvcmF0aW9uOiB7KHMxczIpfXsoczNzNCl9Cg==

`*center`, `*above` and `*below` can also be used to change the default position of the dynamics (until the next default placement is made), but `*center=2`, `*above=2` and `*below=2` are not (yet) implemented.

There can be more complicated cases where two dynamics marks are needed at the same time on the same staff, which involves spine splits:

<img width="986" alt="Screenshot 2023-07-03 at 10 21 13 PM" src="https://github.com/bel28kent/Mysterium/assets/3487289/9d24874c-de2f-4e83-9512-add325b0e15a">

https://verovio.humdrum.org?t=KiprZXJuCSoqa2VybgkqKmR5bmFtCSoqa2VybgkqKmtlcm4JKipkeW5hbQoqc3RhZmY0CSpzdGFmZjMJKnN0YWZmMy80CSpzdGFmZjIJKnN0YWZmMQkqc3RhZmYxLzIKMUMJMWNjCXAJMWNjCTFjYwlmCj0JPQk9CT0JPQk9CioJKgkqCSoJKgkqXgohCSEJIQkhCSEJIUxPOkRZOmE9MgkhCjFFCTFlCWYJMWcJMWcJcAltcAoqCSoJKgkqCSoJKnYJKnYKPQk9CT0JPQk9CT0KKi0JKi0JKi0JKi0JKi0JKi0KISEhc3lzdGVtLWRlY29yYXRpb246IHsoczFzMil9eyhzM3M0KX0K
