### ISSUE TITLE
op71_no02: Rhythms for last measure

### ISSUE THREAD

**Issue by bel28kent** [bel28kent/Mysterium#23]
How would you (@craigsapp) encode the rhythms in the last measure? I know that I cannot have "2.5" because of the decimal, but I am not sure what else to put.

Here is the kern.

<img width="1181" alt="Screen Shot 2023-08-13 at 4 47 12 PM" src="https://github.com/bel28kent/Mysterium/assets/81043032/375581ad-4c5a-416c-bf6d-d646d843b10f">

Here is the error message; it is finding an error with both the "5" and the "2.5." 

<img width="1185" alt="Screen Shot 2023-08-13 at 4 49 00 PM" src="https://github.com/bel28kent/Mysterium/assets/81043032/25d7549c-7c59-4fc6-b0b9-468d7bcf8fd8">

Here is the reference score.

<img width="397" alt="Screen Shot 2023-08-13 at 4 53 11 PM" src="https://github.com/bel28kent/Mysterium/assets/81043032/48fa77c1-5e8f-4487-8a71-d4f37a40fc51">

**Comment by craigsapp** [comment]
There are two rhythm errors: (1) The quintuplet dotted eighth note should be `10.B-` instead of `5B-`, and (2) the quintuplet quarter note should be `5c` instead of `2.5c`.

Rhythms cannot have decimal points in them, so `2.5` is invalid for that reason (there is an extension to `**recip` that could deal with such fractional cases, such as `3%2` which is a triplet whole note (2/3rds of a whole note).

It would be useful to include the Humdrum text for the examples instead of only graphic images of the data (and/or a link to the data in VHV).

Here is what I get:

<img width="493" alt="Screenshot 2023-08-14 at 05 55 00" src="https://github.com/bel28kent/Mysterium/assets/3487289/b711432b-ae90-49dd-8b51-511fd06df0b4">

[View in VHV](https://verovio.humdrum.org?t=KiprZXJuCSoqa2VybgoqY2xlZkY0CSpjbGVmRzIKNHIJNHIKNHIJNHIKKgkqXgohCSFMTzpUWDphOnQ9bGVudG8JIQo0R0cjIDREIDRjCSg0ZWUJMjBlZUxMCi4JLgkyMGNjCi4JLgkyMGEKLgkuCTIwZiMKLgkuCTIwZUpKCioJKnYJKnYKPQk9CipeCSoKKgkqXgkqCioJKgkqXgkqCioJKgkqCSpeCSoKKgkqCSoJKgkqXgkqCioJKlh0dXBsZXQJKlh0dXBsZXQJKlh0dXBsZXQJKlh0dXBsZXQJKlh0dXBsZXQJKgoyMGUtTExcCU5bPjRlLS8JMjByeXkJMTByeXkJMTAucnl5CTVyeXkJMi5mIyAyLmNjIDIuZmZuaTspCjIwYwkuCU5bPjVjLwkuCS4JLgkuCjIwQi0JLgkuCU5bPjEwLkItLwkuCS4JLgoyMEYjCS4JLgkuCU5bMTBGIwkuCS4KWzwyMERESkoJLgkuCS4JLgkyMERELwkuCip2CSp2CSp2CSp2CSp2CSp2CSoKMkREXSAyRiNOXSAyQi1OXSAyY05dIDJlLU5dOwkuCj09CT09CiEhIVJERioqa2VybjogaSA9IGVkaXRvcmlhbCBhY2NpZGVudGFsLCBwYXJlbgohISFSREYqKmtlcm46ID4gPSBhYm92ZQohISFSREYqKmtlcm46IDwgPSBiZWxvdwohISFSREYqKmtlcm46IE4gPSBsaW5rZWQK)

```tsv
**kern	**kern
*clefF4	*clefG2
4r	4r
4r	4r
*	*^
!	!LO:TX:a:t=lento	!
4GG# 4D 4c	(4ee	20eeLL
.	.	20cc
.	.	20a
.	.	20f#
.	.	20eJJ
*	*v	*v
=	=
*^	*
*	*^	*
*	*	*^	*
*	*	*	*^	*
*	*	*	*	*^	*
*	*Xtuplet	*Xtuplet	*Xtuplet	*Xtuplet	*Xtuplet	*
20e-LL\	N[>4e-/	20ryy	10ryy	10.ryy	5ryy	2.f# 2.cc 2.ffni;)
20c	.	N[>5c/	.	.	.	.
20B-	.	.	N[>10.B-/	.	.	.
20F#	.	.	.	N[10F#	.	.
[<20DDJJ	.	.	.	.	20DD/	.
*v	*v	*v	*v	*v	*v	*
2DD] 2F#N] 2B-N] 2cN] 2e-N];	.
==	==
!!!RDF**kern: i = editorial accidental, paren
!!!RDF**kern: > = above
!!!RDF**kern: < = below
!!!RDF**kern: N = linked
```

I had to use the link marker to connect the tie endpoints to each other (either from the tuplets or the spine splits.  In theory these should not be necessary (the link marker `N` needs to go immediately in front of the tie markers).

The B-flat note heads are separated since they have different durations.  This is not yet possible to control in Humdrum, and maybe not yet be controllable in MEI/verovio to merge the two noteheads.  This is related to issue https://github.com/rism-digital/verovio/issues/1569

I merge all of the subspines at once.   The way you do it is safer (I would have to check if my merging does not cause problems when simplifying the spine merges back into a single primary spine).

**Comment by bel28kent** [comment]
Hey Craig - thanks for the response. I will include links to the data in the future. 

Can you comment on how the `!!!RDF**kern: N = linked` impacts using the command-line tools? I.e., if I were to use it for ties between different voices/subspines—which is ubiquitous in Scriabin's music—would an analysis with something like the `beat` command still be accurate? If so, then this method would solve a lot of other complicated problems that I have been encountering in the corpus. Currently, the ties across different voices are represented through doubled notes and added subspines that are not in the original notation. It would also simply subspine assignment.

**Comment by bel28kent** [comment]
@craigsapp Can you follow up on this question about linked ties? If the solution will work, then I should start planning how to make the necessary edits to the corpus. If not, then I will need to pursue other solutions.

> Can you comment on how the `!!!RDF**kern: N = linked` impacts using the command-line tools? I.e., if I were to use it for ties between different voices/subspines—which is ubiquitous in Scriabin's music—would an analysis with something like the `beat` command still be accurate? If so, then this method would solve a lot of other complicated problems that I have been encountering in the corpus. Currently, the ties across different voices are represented through doubled notes and added subspines that are not in the original notation. It would also simplify subspine assignment.

**Comment by craigsapp** [comment]
I figured out the problem that was making the linked ties necessary: The spines needed to be terminated in my encoding for the ties to be processed correctly.  Adding spine terminators allows the ties to be regular:

<img width="1202" alt="Screenshot 2023-08-18 at 08 24 03" src="https://github.com/bel28kent/Mysterium/assets/3487289/e8d0a85d-82af-42f5-95f8-70debb9c9737">

View in [VHV](https://verovio.humdrum.org?t=KiprZXJuCSoqa2VybgoqY2xlZkY0CSpjbGVmRzIKNHIJNHIKNHIJNHIKKgkqXgohCSFMTzpUWDphOnQ9bGVudG8JIQo0R0cjIDREIDRjCSg0ZWUJMjBlZUxMCi4JLgkyMGNjCi4JLgkyMGEKLgkuCTIwZiMKLgkuCTIwZUpKCioJKnYJKnYKPQk9CipeCSoKKgkqXgkqCioJKgkqXgkqCioJKgkqCSpeCSoKKgkqCSoJKgkqXgkqCioJKlh0dXBsZXQJKlh0dXBsZXQJKlh0dXBsZXQJKlh0dXBsZXQJKlh0dXBsZXQJKgoyMGUtTExcCVs+NGUtLwkyMHJ5eQkxMHJ5eQkxMC5yeXkJNXJ5eQkyLmYjIDIuY2MgMi5mZm5pOykKMjBjCS4JWz41Yy8JLgkuCS4JLgoyMEItCS4JLglbPjEwLkItLwkuCS4JLgoyMEYjCS4JLgkuCVsxMEYjCS4JLgpbPDIwRERKSgkuCS4JLgkuCTIwREQvCS4KKnYJKnYJKnYJKnYJKnYJKnYJKgoyRERdIDJGI10gMkItXSAyY10gMmUtXTsJLgo9PQk9PQoqLQkqLQohISFSREYqKmtlcm46IGkgPSBlZGl0b3JpYWwgYWNjaWRlbnRhbCwgcGFyZW4KISEhUkRGKiprZXJuOiA+ID0gYWJvdmUKISEhUkRGKiprZXJuOiA8ID0gYmVsb3cK).


You are using what I call "disjunct" ties by using `[[`.   Ideally the terminator for disjunct ties is `]]` (and middle of a disjunct tie is `__`).    These are used when the two tied notes are not adjacent to each other (these happen often in some Beethoven piano sonatas for example):


<img width="846" alt="Screenshot 2023-08-18 at 08 32 29" src="https://github.com/bel28kent/Mysterium/assets/3487289/e7924ce0-b859-4d87-bc29-0b9e88176e46">

View in [VHV](https://verovio.humdrum.org?t=KiprZXJuCipNMy80Cj0xClsxNmNMTApbMTZlClsxNmcKWzE2Y2NKSgoyY10gZV0gZ10gY2NdCj0KW1sxNmNMTApbWzE2ZQpbWzE2ZwpbWzE2Y2NKSgoyY11dIGVdXSBnXV0gY2NdXQo9CiotCg==).

In the first measure, regular ties are used.  But the tie endings cannot find a matching note immediately after and before the notes with the tie starts/ends.   When this happens the ties are highlighted in red to indicate a data error.   To indicate that this is not an error, the slur endings characters are doubled.   Note that the C5 slur can be encoded with `[`/`]`, so it is not necessary to use the character doubling for that tie (better not to use disjunct ties unless they are needed).

The linked ties are for more complicated cases where automatic identification of the pairings of the endpoints are too difficult to process automatically.   These should be very rare: here is an example that I can think of where notes in different spines need to be tied together:

<img width="846" alt="Screenshot 2023-08-18 at 08 41 30" src="https://github.com/bel28kent/Mysterium/assets/3487289/a5290d1a-bb29-4466-8457-f1d29218971e">

View in [VHV](https://verovio.humdrum.org?t=KiprZXJuCSoqa2VybgoqY2xlZkY0CSpjbGVmRzIKPQk9CjJyCVsyYwoyYz5dCTJyCj0JPQoycglOWzJjCjJjPk5dCTJyCj0JPQoqLQkqLQohISFSREYqKmtlcm46ID4gPSBhYm92ZQohISFSREYqKmtlcm46IE4gPSBsaW5rZWQK).

Linked ties are similar to how MusicXML deals with ties by giving them numbers to match the tie ends.    Cases such as `NN[` or `NNN[` are also possible for multiple linked ties that are active at the same time.  Linked ties are sometimes needed in keyboard music for cross-staff ties (since I treat a piano part as two spines rather than one spine that splits into the top/bottom staff).

---------------

Another category of tie is a *laissez vibrer* (*l.v.*) which has a starting note but no ending note:

<img width="739" alt="Screenshot 2023-08-18 at 08 50 21" src="https://github.com/bel28kent/Mysterium/assets/3487289/4d0b1cad-5acd-4246-810b-f580814a24e4">

View in [VHV](https://verovio.humdrum.org?t=KiprZXJuCipNNC80Cj0xClsyZgoycgo9CiFMTzpUOmx2ClsyZgoycgo9PQoqLQo=).

The first measure has an unterminated tie, but it is treated as a data error (by the Humdrum-to-MEI converter) and displayed in red with verovio.   To assert that the tie is an *l.v.* tie, a layout parameter is prefixed to the starting note in the spine that starts the tie: `!LO:T:lv`, where `T` means it is a tie-related layout parameter, and `lv` is the layout parameter to label the tie as an *l.v.* tie.

Currently there is no control for the length of an *l.v.* tie, but that can be added relatively easily when needed; otherwise, the *l.v.* tie goes to the next rest/note in the spine/subspine.

----------------------

A final special case is the "hanging" tie which goes to the beginning or ending of the music (typically as part of a musical excerpt as in the Polyrhythm Project).   In this case nothing special needs to be done to assert that the incomplete tie is valid:

<img width="739" alt="Screenshot 2023-08-18 at 09 01 10" src="https://github.com/bel28kent/Mysterium/assets/3487289/cdd5fc45-5dad-435e-8764-49bb58e642f5">

View in [VHV](https://verovio.humdrum.org?t=KiprZXJuCipNNC80Cj0KMmZdCjJyCj0KMnIKWzJmCj09CiotCg==).

In this situation, the ties are automatically attached to the ending barline, or "time 0" at the beginning of the first measure.

**Comment by craigsapp** [comment]
Here are some adjustments that matches close to the original:

<img width="237" alt="image" src="https://github.com/bel28kent/Mysterium/assets/3487289/2679d54a-d47f-406f-b4dd-6ffd569d69e8">


<img width="1031" alt="Screenshot 2023-08-18 at 19 09 52" src="https://github.com/bel28kent/Mysterium/assets/3487289/b30a6879-c002-423e-991e-f018df3c3772">

View in [VHV](https://verovio.humdrum.org?t=ISEhQ09NOiBTY3JpYWJpbiwgQWxleGFuZGVyCiEhIU9UTEBARlI6IFBvw6htZQohISFPVExAQEVOOiBQb2VtCiEhIU9QUkBARlI6IDIgUG/DqG1lcwohISFPUFJAQEVOOiAyIFBvZW1zCiEhIU9QUzogNjkKISEhT05NOiAxCiEhIU9EVDogMTkxMwohISFBR046IFBvZW0KKiprZXJuCSoqa2VybgkqKmR5bmFtCipjbGVmRjQJKmNsZWZHMgkqCiprW10JKmtbXQkqCipNMy80CSpNMy80CSoKPTM1CT0zNQk9MzUKW1szMnFCLUxMTC8JLgkuCltbMzJxZG4JLgkuCltbMzJxZW4JLgkuCltbMzJxZ24JLgkuCk5bWzwzMnFiLT4JLgkuCk5bPDMycWVlPkpKSgkuCS4KWzIuQ0MgWzIuQyAyLkItXyAyLmRfIDIuZV8gMi5nXwkyLmItTl9fIDIuZWVOXyBbMi5iYi0JLgo9MzYJPTM2CT0zNgoyLkNDXSAyLkNdIDIuQi1dXSAyLiBkXV0gMi5lXV0gMi5nXV0JMi5iLU5dXSAyLmVlTl0gMi5iYi1dCS4KPT0JPT0JPT0KKi0JKi0JKi0KISEhUkRGKiprZXJuOiA8ID0gYmVsb3cKISEhUkRGKiprZXJuOiA+ID0gYWJvdmUKISEhUkRGKiprZXJuOiBOID0gbGlua2VkCiEhIXN5c3RlbS1kZWNvcmF0aW9uOiB7KCopfQohISFFTkM6IEJyeWFuIEphY29iIEJlbGwKISEhRU5EOiBOb3ZlbWJlciAyMDIxIHRvIEFwcmlsIDIwMjIKISEhUEVEOiBHw7xudGVyIFBoaWxpcHAKISEhUFRMOiBBdXNnZXfDpGhsdGUgS2xhdmllcndlcmtlIChFZGl0aW9uIFBldGVycykK).

The link signifiers (`N`) need to be placed on the tie-continuation notes (first half note chord).   Then the `N` should also be added on the next chord since they had to be added to the `_`/`__` tied notes.


What does `qqq` mean?   I would use a single `q` in this case.

**Comment by bel28kent** [comment]
I added the same number of qs as the number of beams. I did this after I first converted the krn files from MusicXML because I noticed that there were multiple qs if the note was smaller than an eighth note. Here is a quick example in krn; I encoded it first in Finale and then converted with `musicxml2hum`.

``
**kern
*clefG2
*k[]
*C:
*M3/4
=1
8qc/
4c
16qqc/LL
16qqc/
16qqc/
16qqc/JJ
4c
32qqc/LLL
32qqc/
32qqc/
32qqc/JJJ
4c
==
*-
``

Though looking at this now, there are two qs for both the 16ths and 32nds.

**Comment by craigsapp** [comment]
Roughly speaking a single `q` means an acciaccatura, which is an unaccented note just before the beat, and `qq` is an appoggiatura or accented grace note which should be played on the beat, stealing time from the note that follows it.

Single `q`. notes will have a slash on the stem, and `qq` grace notes will not.   Typically groups of grace notes beamed together are the `q` type (but traditionally do not have a slash through the beam, although there are modern styles that display a slash on the beam of such grace note groups).

Examples:


<img width="773" alt="Screenshot 2023-08-18 at 21 53 52" src="https://github.com/bel28kent/Mysterium/assets/3487289/efea70fa-bedc-4165-bacc-6d9169f42210">

View in [VHV](https://verovio.humdrum.org?t=KiprZXJuCj0KNHJ5eQo4cWcKNGYKMnIKOHFxZwo0Zgo0cnl5Cj0KOHFnCjRmCjE2cWcKNGYKMzJxZwo0Zgo2NHFnCjRmCj0KOHFxZwo0ZgoxNnFxZwo0ZgozMnFxZwo0Zgo2NHFxZwo0Zgo9CjE2cWZMTAoxNnFnSkoKMmYKMzJxZkxMTAozMnFnSkpKCjJmCj0KKi0K).

The rhythms on grace notes are visual only, and when analyzing the score they are treated as 0 duration notes (due to the presence of the `q` in the token).   For appoggiaturas, they typically indicate the duration to steal from the following note.

**Comment by bel28kent** [comment]
Okay. I can correct this easily using `sed`.

**Comment by craigsapp** [comment]
Also I have a sed-like tool in VHV called shed:

```
shed -ke "s/qq/q/"
```

<img width="773" alt="Screenshot 2023-08-18 at 22 11 05" src="https://github.com/bel28kent/Mysterium/assets/3487289/039557c0-10e4-49be-94f2-cbdb355a7983">

View in [VHV](https://verovio.humdrum.org?t=KiprZXJuCj0KNHJ5eQo4cWcKNGYKMnIKOHFxZwo0Zgo0cnl5Cj0KOHFnCjRmCjE2cWcKNGYKMzJxZwo0Zgo2NHFnCjRmCj0KOHFxZwo0ZgoxNnFxZwo0ZgozMnFxZwo0Zgo2NHFxZwo0Zgo9CjE2cWZMTAoxNnFnSkoKMmYKMzJxZkxMTAozMnFnSkpKCjJmCj0KKi0K&filter=shed%20-ke%20%22s%2Fqq%2Fq%2F%22).

This will convert `qq` to `q` in all data tokens in the file (but not changing "qq" in comments or reference records, or interpretations.   If you have humlib tools installed on the command-line you could do this in a directory:

```bash
for file in *.krn
do
      echo processing $file
     shed -ke "s/qqq/q/" $file > $file.temp && mv $file.temp $file
done
```

The `-k` option will only process `**kern` spines (ignoring "qqq" in any other spine types (so it is safer in general than plain sed, although I doubt you have "qqq" anywhere else in the files).

**Comment by bel28kent** [comment]
Tie issue now subsumed under [issue for 2.1 round of edits](https://github.com/bel28kent/Mysterium/issues/22) as it is effectively a subspine issue.
