### ISSUE TITLE
Tab replaced with space in op 8/3

### ISSUE THREAD

**Issue by craigsapp** [bel28kent/Mysterium#38]
In scriabin-op08-n03.krn, there it a space instead of a tab:

<img width="412" alt="Screenshot 2024-02-25 at 18 25 07" src="https://github.com/bel28kent/Mysterium/assets/3487289/3a08c841-6d39-4eb0-a81d-c71f7e93e281">

(The gray box highlights where the space should be converted into a tab).

**Comment by bel28kent** [comment]
I will resolve this in April/May, when I am planning on finishing the corpus, unless you need a change to the server copy before then.

**Comment by craigsapp** [comment]
No hurry.

**Comment by bel28kent** [comment]
The problem was that the awk script that I wrote some time back to find errors didn't take record type into account (e.g., reference record, interpretation, etc.) So it couldn't handle the use case where you have spaces on an interpretation record because I ignored spaces in the tab-spaced columns due to the complexity of nested spaces in stops. I have written a more robust Perl program that handles this. I then wrapped that in another Perl program that filters out files that don't actually have spacing errors.

For the main branch, this resulted in the following files being found to have errors:
<img width="1920" alt="Screen Shot 2024-03-31 at 5 43 57 PM" src="https://github.com/bel28kent/Mysterium/assets/81043032/61cca38f-ad53-492b-8ccb-69ffca0e014c">


For the editing branch, this resulted in the following files being found to have errors:
<img width="1920" alt="Screen Shot 2024-03-31 at 5 41 56 PM" src="https://github.com/bel28kent/Mysterium/assets/81043032/71cba537-3aee-4978-9c77-f6606e8cd9ed">

**Comment by bel28kent** [comment]
On main, the sole error in `scriabin-op08_no03.krn` is spaces on an interpretation record:
<img width="1920" alt="Screen Shot 2024-03-31 at 5 51 40 PM" src="https://github.com/bel28kent/Mysterium/assets/81043032/d376d639-c9f6-4495-86d3-66495fde212c">

**Comment by bel28kent** [comment]
For the editing branch, the error in `scriabin-op08_no03.krn` is the same.

For `scriabin-op07_no01.krn` these two records have too many tabs:
<img width="1920" alt="Screen Shot 2024-03-31 at 5 58 38 PM" src="https://github.com/bel28kent/Mysterium/assets/81043032/3c8f5084-6ad9-48d6-8c6c-02989e765f51">

**Comment by bel28kent** [comment]
Errors on editing branch fixed in ce277d74185afe788b2a176850ef4d12755008d2
